---
# Role handlers

- name: Reboot # noqa ignore-errors
  shell: >-
    sleep {{ reboot_delay }}
    && shutdown -r now 'Ansible reboot role triggered a reboot'
  args:
    warn: no
  async: 1
  poll: 0
  changed_when: yes
  failed_when: no
  ignore_errors: yes
  listen:
    - reboot
    - reboot host
  when:
    - ansible_virtualization_type | default("") != "docker"
    - not reboot_disable
  check_mode: no

- name: Reboot wait
  wait_for_connection:
    sleep: "{{ reboot_wait_sleep }}"
    delay: "{{ reboot_wait_delay }}"
    timeout: "{{ reboot_wait_timeout | default(300) }}"
  changed_when: no
  when:
    - ansible_virtualization_type | default("") != "docker"
    - not reboot_disable
  listen:
    - reboot wait
    - wait host
  check_mode: no
